### ISSUE TITLE
[Feat] 디바이스 등록 User 개발

### ISSUE THREAD

**Issue by dudrhy12** [SMWU-Cookiee/Cookiee-Server#4]
## DESCRIPTION
별도의 회원가입 없이 디바이스 등록으로 User 기능 개발

## TODO
- [x] 디바이스 ID로 User 등록 가능한 Controller, Service 코드 개발
- [x] UserV1 domain, repository, dto 개발
- [ ] Test 코드 작성

## ETC
추후 API 버전 분리 필요
