### ISSUE TITLE
[Feat] Swagger 설정

### ISSUE THREAD

**Issue by dudrhy12** [SMWU-Cookiee/Cookiee-Server#7]
## DESCRIPTION
Swagger(API 자동화 문서) 연결

## TODO
- [x] Swagger dependency 추가
- [x] Swagger Config 설정
- [ ] Swagger 문서 배포
